import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";

//Fonts
//__Start__
const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"]
})
//__End__


//Meta Data
//__Start__
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//__End__


//Layout
//__Start__
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakarta.variable}`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
//__End